name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      service-name-gitVersion:
        image: gittools/gitversion:5.6.11-alpine.3.12-x64-3.1
        volumes: 
          - "./:/repo"
      
    steps:
      - name: Assign variables
        run: |
          echo "${{ steps.gitversion.outputs.semVer }}"
