name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Version
      id: gitversion
      uses: docker://gittools/gitversion:5.6.11-alpine.3.12-x64-3.1
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
      env:
        SEMVER: $GitVersion_FullSemVer
        BRANCHNAME: $GitVersion_BranchName
          
    - name: Assign variables
      run: |
        echo "${{ steps.gitversion.outputs.fullSemVer }}"
        echo "${{ steps.gitversion.outputs.branchname }}"
