name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    #- run: GitVersion
    
    - name: GitVersion
      id: gitversion
      uses: nmcc/actions-gitversion@v1
      with:
        path-to-gitversion: packages/GitVersion.CommandLine/tools/GitVersion.exe
                  
    - name: Assign variables
      run: |
        echo "${{ steps.gitversion.outputs.SemVer }}"
        echo "${{ steps.gitversion.outputs.BranchName }}"
        #cat /home/runner/work/gitversionactiontest/gitversionactiontest/branch.txt
        
    - name: "Trigger jenkins job"
      uses: stigmelling/jenkins-action@v1
      with:
        jenkinsUrl: ${{ secrets.JENKINS_URL }}
        token: ${{ secrets.JENKINS_TOKEN }}
        username: "admin"
        job: "job/Sandbox/job/GitVersionActionTest"
        params: "{'semver': '${{ steps.gitversion.outputs.SemVer }}', 'branchname': '${{ steps.gitversion.outputs.BranchName }}' }"
   
    - name: Get job status
      run: echo "Job status is ${{ steps.job-build.outputs.job_status }}"
