name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.801'
    - uses: actions/setup-gitversion@v1.0.0
      with:
        gitversion-version: 5.1.1
    - run: GitVersion
    
    - name: Check the directory
      run: ls -a
    
    - name: GitVersion
      id: gitversion
      uses: nmcc/actions-gitversion@v1
      with:
        path-to-gitversion: /home/runner/work/gitversionactiontest/gitversionactiontest/packages/GitVersion.CommandLine/tools/GitVersion.exe
        
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.gitversion.outputs.SemVer }}
          
    - name: Assign variables
      run: |
        echo "${{ steps.gitversion.outputs.SemVer }}"
        echo "${{ steps.gitversion.outputs.BranchName }}"
        #cat /home/runner/work/gitversionactiontest/gitversionactiontest/branch.txt
