name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: GitVersion
      id: gitversion
      uses: nmcc/actions-gitversion@v1
      with:
        path-to-gitversion: packages/GitVersion.CommandLine/tools/GitVersion.exe
        
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.gitversion.outputs.SemVer }}
          
    - name: Assign variables
      run: |
        echo "${{ steps.gitversion.outputs.SemVer }}"
        echo "${{ steps.gitversion.outputs.BranchName }}"
        #cat /home/runner/work/gitversionactiontest/gitversionactiontest/branch.txt
