name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      service-name-gitVersion:
        image: gittools/gitversion:5.6.11-alpine.3.12-x64-3.1
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run Docker Command
        run: echo "::set-output name=git-version::$(docker run --rm -v $(pwd):/repo gittools/gitversion:5.6.11-alpine.3.12-x64-3.1 /repo)"
        id: git_version
          
      - name: Assign variables
        run: |
          ls -a
          cat "$(pwd)gitversion.properties"
