name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch "echo $GitVersion_FullSemVer > /github/workspace/version.txt"
          
    - name: Assign variables
      run: |
        ls -a /github/workspace
        cat "/github/workspace/version.txt"
